name: gradle publish
on: 
  push: 
    branches:
    - master
jobs:
  build:
    runs-on: self-hosted
    steps:
     -  name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


