name: gradle publish
on: 
  push: 
    branches:
    - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: build-package
        uses: - echo -n CommonEpisilia  | docker login --username epcommon --password-stdin
