name: gradle publish
on: 
  push: 
    branches:
    - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: build-package
        run: ./gradlew build
      - name: publish-package
        run: gradle publish 
